"""123

Revision ID: 36f8f3a69137
Revises: 62a6079b1cae
Create Date: 2020-04-21 06:31:46.426511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f8f3a69137'
down_revision = '62a6079b1cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('discription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'discription')
    # ### end Alembic commands ###
